#!/usr/bin/env python3
"""
Generate synthetic banking transaction logs and ingest them into Dynatrace.

Sends log records to /api/v2/logs/ingest with log.source=banking.transaction.
These are the logs that the fraud detection workflows query.

Account IDs match the format generated by generate_beneficiaries.py
(e.g. NL00000000) so join-based detection works out of the box.

Usage:
  python3 generate_logs.py [n_transactions] [n_accounts]

Defaults: 200 transactions across 20 accounts
"""
import json
import random
import re
import sys
import os
import datetime
import urllib.request
import urllib.error

N_TRANSACTIONS = int(sys.argv[1]) if len(sys.argv) > 1 else 200
N_ACCOUNTS     = int(sys.argv[2]) if len(sys.argv) > 2 else 20

COUNTRY_CODES     = ["NL", "DE", "FR", "GB", "BE", "ES", "IT", "US", "PL", "CH",
                     "AT", "SE", "DK", "NO", "AE", "SG", "JP", "AU", "CA", "ZA"]
TRANSACTION_TYPES = ["CREDIT_TRANSFER", "WIRE_TRANSFER", "PAYMENT", "DIRECT_DEBIT"]
CURRENCIES        = ["EUR", "USD", "GBP"]

# ── Load .env from repo root ──────────────────────────────────────────────────
_env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env")
try:
    with open(_env_path) as _f:
        for _line in _f:
            _line = _line.strip()
            if not _line or _line.startswith("#") or "=" not in _line:
                continue
            _k, _, _v = _line.partition("=")
            os.environ.setdefault(_k.strip(), _v.strip().strip('"').strip("'"))
except FileNotFoundError:
    pass

# ── Generate transactions ─────────────────────────────────────────────────────
def generate(n: int, n_accounts: int) -> list[dict]:
    cc = COUNTRY_CODES
    # Account IDs in the same format as generate_beneficiaries.py
    account_ids = [f"{cc[i % len(cc)]}{i:08d}" for i in range(n_accounts)]

    # ~80% go to accounts that will become "known" after the first lookup refresh;
    # ~20% go to XX-prefixed accounts that will always be new.
    # On the very first run (empty lookup) ALL completed transactions trigger.
    # After dql-to-lookup runs once, only the XX ones keep firing.
    known_pool = account_ids * 5
    new_pool   = [f"XX{i:08d}" for i in range(n * 2)]

    now   = datetime.datetime.now(datetime.timezone.utc)
    today = now.strftime("%Y%m%d")
    txns  = []

    for i in range(n):
        account_id  = random.choice(account_ids)
        # ~20% chance of a new beneficiary to trigger fraud detection; never self-send
        pool        = new_pool if random.random() < 0.2 else [b for b in known_pool if b != account_id]
        beneficiary = random.choice(pool)
        amount      = round(random.uniform(10, 15_000), 2)
        currency    = random.choice(CURRENCIES)
        txn_type    = random.choice(TRANSACTION_TYPES)
        status      = "COMPLETED" if random.random() < 0.85 else random.choice(["FAILED", "PENDING"])
        ts_offset   = random.randint(0, 270)   # spread within last 4.5 min so fetch logs from:now()-5m catches them
        ts          = (now - datetime.timedelta(seconds=ts_offset)).strftime("%Y-%m-%dT%H:%M:%S.000Z")

        txns.append({
            "timestamp":           ts,
            "severity":            "INFO",
            "content":             f"banking.transaction {txn_type} {account_id} -> {beneficiary} {amount} {currency} {status}",
            "log.source":          "banking.transaction",
            "account.id":          account_id,
            "beneficiary.account": beneficiary,
            "transaction.id":      f"TXN-{today}-{i+1:04d}",
            "transaction.amount":  str(amount),
            "transaction.currency": currency,
            "transaction.type":    txn_type,
            "transaction.status":  status,
        })

    return txns

# ── POST to Dynatrace Logs Ingest API ─────────────────────────────────────────
def ingest(env_url: str, token: str, records: list[dict], batch_size: int = 1000) -> None:
    endpoint = f"{env_url}/api/v2/logs/ingest"
    total    = 0
    for start in range(0, len(records), batch_size):
        batch   = records[start : start + batch_size]
        payload = json.dumps(batch).encode()
        for attempt in range(2):
            req = urllib.request.Request(
                endpoint,
                data=payload,
                headers={
                    "Authorization": f"Api-Token {token}",
                    "Content-Type":  "application/json; charset=utf-8",
                },
                method="POST",
            )
            try:
                with urllib.request.urlopen(req):
                    break
            except urllib.error.HTTPError as e:
                body = e.read().decode()
                # DT Gen3 environments route classic APIs to a different subdomain.
                # The 404 body contains the correct URL — extract and retry once.
                if e.code == 404 and attempt == 0:
                    m = re.search(r"'(https://[^']+)'", body)
                    if m:
                        endpoint = m.group(1).rstrip("/") + "/api/v2/logs/ingest"
                        print(f"  Switching to API domain: {endpoint}", flush=True)
                        continue
                print(f"ERROR {e.code}: {body}", file=sys.stderr)
                sys.exit(1)
        total += len(batch)
        print(f"  Sent {total}/{len(records)}", flush=True)

# ── Main ──────────────────────────────────────────────────────────────────────
env_url = os.environ.get("DT_ENV_URL", "").rstrip("/")
token   = os.environ.get("DT_API_TOKEN", "").strip()

if not env_url:
    print("ERROR: DT_ENV_URL not set. Add it to .env or export it.", file=sys.stderr)
    sys.exit(1)
if not token:
    print("ERROR: DT_API_TOKEN not set. Add it to .env or export it.", file=sys.stderr)
    sys.exit(1)
if token.startswith("Api-Token "):
    token = token[len("Api-Token "):]

print(f"Environment: {env_url}")

print(f"\nGenerating {N_TRANSACTIONS} transactions across {N_ACCOUNTS} accounts...")
txns      = generate(N_TRANSACTIONS, N_ACCOUNTS)
completed = sum(1 for t in txns if t["transaction.status"] == "COMPLETED")
flagged   = sum(1 for t in txns if t["beneficiary.account"].startswith("XX"))
print(f"  {completed} COMPLETED, {N_TRANSACTIONS - completed} other")
print(f"  ~{flagged} with XX-prefixed beneficiaries (always new)")
print(f"  Note: on first run all {completed} COMPLETED will trigger (empty lookup).")
print(f"  After dql-to-lookup runs once, only the ~{flagged} XX ones keep firing.")

print("\nIngesting...")
ingest(env_url, token, txns)
print(f"\nDone. {N_TRANSACTIONS} log records sent.")
print("\nVerify with DQL:")
print('  fetch logs, from:now()-1h | filter `log.source` == "banking.transaction" | sort timestamp desc')
